// <auto-generated />
using System;
using ClassroomBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClassroomBackend.Migrations
{
    [DbContext(typeof(ClassroomDbContext))]
    [Migration("20260516133120_AddRecordingStagingFields")]
    partial class AddRecordingStagingFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("ClassroomBackend.Models.QuizAttemptRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("QuizAttempts");
                });

            modelBuilder.Entity("ClassroomBackend.Models.RecordingCronReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CheckedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeletedOldErrorCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeletedOldUploadedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DriveMissingCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("InterruptedCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SummaryJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UploadFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UploadedCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RecordingCronReports");
                });

            modelBuilder.Entity("ClassroomBackend.Models.RecordingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CalendarEventId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriveContentLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DriveFileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DriveFolderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DriveViewLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastCheckError")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastCheckedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastUploadAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MeetingCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordingSessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StagedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StoppedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeacherEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TempFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UploadAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UploadError")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RecordingSessions");
                });

            modelBuilder.Entity("ClassroomBackend.Models.SyncLogRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Object")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SyncLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
